### ISSUE TITLE
v2ray docker 返回 invaild user

### ISSUE THREAD

**Issue by alexliu4u** [v2ray/discussion#72]
你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务端：
abisoft/caddy:latest
v2ray/official:latest
客户端：
BifrostV

你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
手机访问google.com

你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法访问此网站
连接关闭

请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_CLOSED

你期待看到的正确表现是怎样的？
正常访问。

请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务端 config.json
```
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "info"
    },
    "inbound": {
        "port": 20000,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "uuid",
                    "level": 1,
                    "alterId": 64,
                    "security": "auto"
                }
            ]
        }
    },
    "streamSettings": {
     "network": "ws",
     "wsSettings": {
         "path": "/lad"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}
```

Caddyfile：
```
http://xxx.com {
  redir https://xxx.com{uri}
}

https://xxx.com {
  root /srv
  gzip
  log stdout
  index index.html
  tls xxx@gmail.com
  errors {
    404 404.html
  }
  proxy /lad ladder_b:20000{
    websocket
  }
}
```
yml:
```
version: '3.7'
services:
  v2ray:
    image: v2ray/official:latest
    restart: always
    volumes:
     - /var/log/v2ray:/var/log/v2ray
     - /var/local/v2ray:/etc/v2ray
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
    ports:
     - "20000:20000"
    command: "v2ray -config=/etc/v2ray/config.json"
    container_name: ladder_b
    networks:
     - ladder-network

  caddy:
    image: abiosoft/caddy:latest
    restart: always
    volumes:
     - /var/local/caddy/ladder/www:/srv
     - /var/local/caddy/ladder/Caddyfile:/etc/Caddyfile
     - /var/local/caddy/ladder/www/.certs:/root/.caddy
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - v2ray
    container_name: ladder_f
    networks:
     - ladder-network
networks:
  ladder-network:
    driver: bridge
```

v2ray log:

access.log
```
2018/11/17 22:30:05 192.168.192.3:35726 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2018/11/17 22:30:06 192.168.192.3:35728 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2018/11/17 22:30:07 192.168.192.3:35730 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
```

error.log:
```
2018/11/17 22:30:09 [Info] [3668121721] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 192.168.192.3:35738 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/11/17 22:30:10 [Info] [4207579940] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 192.168.192.3:35740 > v2ray.com/core/proxy/vmess/encoding: invalid user
```

caddy log:
```
17/Nov/2018:23:46:03 +0000 [ERROR 502 /lad] EOF
[17/Nov/2018:23:02:50 +0000] "GET /lad HTTP/1.1" 502 16
```

客户端配置:
```
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "listen": "127.0.0.1",
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    },
    "sniffing": {
      "enabled": false,
      "destOverride": [
        "http",
        "tls"
      ]
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxx.com",
          "port": 443,
          "users": [
            {
              "id": "uuid",
              "alterId": 64,
              "security": "auto",
              "level": 1
            }
          ]
        }
      ]
    },
    "tag": "proxy",
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "xxx.com",
        "allowInsecure": true
      },
      "wsSettings": {
        "path": "\/lad",
        "headers": {}
      }
    },
    "mux": {
      "enabled": true,
      "concurrency": 8
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "policy": {
    "level": {
      "1": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "bufferSize": 1024
      }
    }
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```
